### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by fleimgruber** [grktsh/python-oas#12]
It would be nice to provide an example of user code in the README. If you give me the appropriate pointers into the code, I could come up with an example and make a PR.

**Comment by grktsh** [comment]
@fleimgruber Thank you. Here is the example for Falcon: https://github.com/grktsh/falcon-oas/blob/380921e82a50b565b3df6e494b06cc9dba961db7/src/falcon_oas/middlewares.py#L106

In summary, first, create a [Spec](https://github.com/grktsh/python-oas/blob/71d60a1ada62c07bb0be10c10232aea811f1b3d3/src/oas/spec.py#L24) instance with `oas.create_spec_from_dict()` and for each request:
1. [L107] Create an instance of the subclass of `oas.Request`.
1. [L109] Find Operation Object for the request instance. If the media type of the request body is unmet, `oas.exceptions.UndocumentedMediaType` is raised.
1. [L115] Create `oas.SchemaUnmarshaler` instance.
1. [L122] Unmarshal the request and obtain unmarshaled paramters and request body. If unmarshaling fails, `oas.exceptions.UnmarshalError` is raised.

**Comment by grktsh** [comment]
@fleimgruber I added the example section to README. If there are unclear points, feel free to reopen the issue and/or make a PR.

**Comment by fleimgruber** [comment]
@grktsh Thanks for putting this together and sorry for not getting back to this earlier. Will have a look and let you know in case!
