### ISSUE TITLE
Unmarshaler for `additionalProperties` with object value incorrect?

### ISSUE THREAD

**Issue by sisp** [grktsh/python-oas#5]
If I'm not mistaken, the unmarshaler for `additionalProperties` with an object value is incorrect.

The [unit test](https://github.com/grktsh/python-oas/blob/e6cc018a6f5150ff5eaca1a44adabfc818d5be55/tests/schema/test_unmarshalers.py#L98-L122) tests the following value assigned to `additionalProperties`:

```json
{
  "additionalProperties": {
    "x": {
      "type": "string"
    }
  }
}
```

The [JSON Schema Draft 4](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.4.1) states:

> The value of "additionalProperties" MUST be a boolean or an object. If it is an object, it MUST also be a valid JSON Schema.

An [example from Draft 7](https://json-schema.org/understanding-json-schema/reference/object.html) (I didn't find one for Draft 4, but I think there is no difference in this case) looks like this:

```json
{
  "additionalProperties": { "type": "string" }
}
```

I think the problem is that the unmarshaler treats `additionalProperties` the same way as `properties` when `additionalProperties` is an `object`/`dict`:

https://github.com/grktsh/python-oas/blob/e6cc018a6f5150ff5eaca1a44adabfc818d5be55/src/oas/schema/unmarshalers.py#L75-L76

Instead, I think `properties` should be unmarshaled as it's done now, but any remaining instance properties should be unmarshaled using the `additionalProperties` subschema, if present, using [`SchemaUnmarshaler::_unmarshal`](https://github.com/grktsh/python-oas/blob/e6cc018a6f5150ff5eaca1a44adabfc818d5be55/src/oas/schema/unmarshalers.py#L22). The results of both unmarshalers should then be merged. Do you agree?

**Comment by grktsh** [comment]
Sorry, my mistake!

**Comment by grktsh** [comment]
[OpenAPI 3.0.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md) says:

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

So if `additionalProperties` is absent, should remaining instance properties be merged as it is?

**Comment by sisp** [comment]
I think so, good point. I've added a line comment in #9. What do you think?

**Comment by sisp** [comment]
And what is the result of unmarshaling when `{"additionalProperties": {}}`? Is this equivalent to `{"additionalProperties": true}`?

**Comment by grktsh** [comment]
Yes, I think the following are equivalent:
- `{}`
- `{"additionalProperties": {}}`
- `{"additionalProperties": true}`
