### ISSUE TITLE
Unmarshaler for `additionalProperties` with value `true` incorrect

### ISSUE THREAD

**Issue by sisp** [grktsh/python-oas#7]
I believe the unmarshaler for `additionalProperties` when `{"additionalProperties": true}` is incorrect because the unmarshaler only unmarshals properties stated in `properties`:

https://github.com/grktsh/python-oas/blob/e6cc018a6f5150ff5eaca1a44adabfc818d5be55/src/oas/schema/unmarshalers.py#L79

If `{"additionalProperties": true}` all remaining properties not stated in `properties` or matched by `patternProperties` (see #6) should be extracted without a schema, too.

**Comment by grktsh** [comment]
Fixed by #9
